### ISSUE TITLE
Figma tasarımının yapılması

### ISSUE THREAD

**Issue by muffafa** [yazilimcukurova/yazilimcukurova-web-app#3]

**Comment by Eledhwen0** [comment]
Deneme

**Comment by muffafa** [comment]
tasarım linki;

https://www.figma.com/file/jx0vc3anUDYViOaA3TXi5u/Untitled?type=design&node-id=0%3A1&mode=design&t=E9mG6vLm9VcXghvj-1

**Comment by muffafa** [comment]
Şuanki hali

![image](https://github.com/yazilimcukurova/yazilimcukurova-web-app/assets/62511949/f020ba27-0a38-43a2-85fd-f2871d761212)

**Comment by muffafa** [comment]
Fikirler 

https://youtu.be/_A-0ZOVfKro

bu bi kere bu bitince de sürekli olarak 100. yıl marşı loppp

**Comment by Eledhwen0** [comment]
![Image](https://github.com/yazilimcukurova/yazilimcukurova-web-app/assets/111533066/5ecba204-fb76-4cd4-b6b4-0219741804a9)

son hali

**Comment by muffafa** [comment]
![yc-hatira-gazete-100](https://github.com/yazilimcukurova/yazilimcukurova-web-app/assets/62511949/d478b442-407a-4671-be16-f0a3a9aa7479)
